from dataclasses import dataclass
from pathlib import Path
from typing import Any
import json
import math

import numpy as np
import pandas as pd

TOOLBOX_VERSION = "2026-07-27-pydantic-fix-2"

try:
    import geopandas as gpd
except ImportError:
    gpd = None


DEFAULT_COMPARISON_METRICS = [
    "overall_score",
    "demand_score",
    "coverage_score",
    "accessibility_score",
    "feasibility_score",
    "equity_score",
    "capacity_filled",
    "population_1000m",
    "traffic_volume_weighted_1000m",
    "distance_to_nearest_charger_m",
    "existing_chargers_2000m",
]

# This direction metadata is used only for deterministic comparison summaries.
# It does not recalculate any score.
METRIC_DIRECTIONS = {
    "overall_score": "higher",
    "demand_score": "higher",
    "coverage_score": "higher",
    "accessibility_score": "higher",
    "feasibility_score": "higher",
    "equity_score": "higher",
    "capacity_filled": "higher",
    "population_1000m": "higher",
    "traffic_volume_weighted_1000m": "higher",
    "distance_to_nearest_charger_m": "higher",
    "existing_chargers_2000m": "lower",
}


def _json_safe(value: Any) -> Any:
    """Convert pandas, NumPy, and datetime values into JSON-safe Python values."""
    if value is None:
        return None

    if isinstance(value, (np.integer,)):
        return int(value)

    if isinstance(value, (np.floating,)):
        if np.isnan(value) or np.isinf(value):
            return None
        return float(value)

    if isinstance(value, (np.bool_,)):
        return bool(value)

    if isinstance(value, pd.Timestamp):
        return value.isoformat()

    if isinstance(value, Path):
        return str(value)

    if isinstance(value, dict):
        return {
            str(key): _json_safe(item)
            for key, item in value.items()
        }

    if isinstance(value, (list, tuple, set)):
        return [_json_safe(item) for item in value]

    try:
        if pd.isna(value):
            return None
    except (TypeError, ValueError):
        pass

    return value


def _records(frame: pd.DataFrame) -> list[dict[str, Any]]:
    """Convert a DataFrame to clean JSON-safe records."""
    return [
        {
            str(key): _json_safe(value)
            for key, value in row.items()
        }
        for row in frame.to_dict(orient="records")
    ]


def _normalize_identifier(value: Any) -> str:
    return str(value).strip()


@dataclass(frozen=True)
class ToolFilePaths:
    candidate_summary: Path
    selected_sequence: Path
    configuration: Path
    scored_candidates_geojson: Path
    selected_sites_geojson: Path
    scenario_results: Path
    sensitivity_results: Path


class GeoPlanToolbox:
    """
    Deterministic evidence toolbox for the GeoPlan multi-agent workflow.

    The class loads compact outputs generated by the GIS notebook and exposes
    read-only functions suitable for wrapping with LlamaIndex FunctionTool.
    It never asks an LLM to calculate spatial relationships.
    """

    def __init__(
        self,
        project_root: str | Path,
        *,
        strict: bool = True,
    ) -> None:
        self.project_root = Path(project_root).expanduser().resolve()
        self.output_dir = self.project_root / "outputs"
        self.processed_dir = self.project_root / "data" / "processed"

        self.paths = ToolFilePaths(
            candidate_summary=(
                self.output_dir / "agent_candidate_summary.json"
            ),
            selected_sequence=(
                self.output_dir / "selected_site_sequence.csv"
            ),
            configuration=(
                self.output_dir / "planning_configuration.json"
            ),
            scored_candidates_geojson=(
                self.processed_dir
                / "scored_ev_charging_candidates.geojson"
            ),
            selected_sites_geojson=(
                self.processed_dir
                / "selected_ev_charging_sites.geojson"
            ),
            scenario_results=(
                self.output_dir / "scenario_results.csv"
            ),
            sensitivity_results=(
                self.output_dir / "sensitivity_results.csv"
            ),
        )

        self.strict = strict
        self._load()

    @staticmethod
    def locate_project_root(
        start: str | Path | None = None,
    ) -> Path:
        """
        Locate a GeoPlan project containing outputs and data folders.

        The search checks the starting directory, its parents, and a nested
        geoplan_data_preparation directory.
        """
        current = Path(start or Path.cwd()).expanduser().resolve()

        candidates: list[Path] = []
        for candidate in [
            current,
            current / "geoplan_data_preparation",
            current.parent,
            current.parent / "geoplan_data_preparation",
            *current.parents,
        ]:
            if candidate not in candidates:
                candidates.append(candidate)

        for candidate in candidates:
            has_outputs = (candidate / "outputs").is_dir()
            has_data = (candidate / "data").is_dir()
            if has_outputs and has_data:
                return candidate

        return current

    def _required_missing(self) -> list[Path]:
        required = [
            self.paths.candidate_summary,
            self.paths.selected_sequence,
            self.paths.configuration,
        ]
        return [path for path in required if not path.exists()]

    def _load(self) -> None:
        missing = self._required_missing()

        if missing and self.strict:
            formatted = "\n".join(f"- {path}" for path in missing)
            raise FileNotFoundError(
                "Required GeoPlan agent outputs are missing:\n"
                f"{formatted}\n\n"
                "Run the export section of the deterministic site-selection "
                "notebook before building the agent tools."
            )

        self.candidates = self._load_candidates()
        self.selected_sequence = self._load_selected_sequence()
        self.configuration = self._load_configuration()
        self.scenario_results = self._load_optional_csv(
            self.paths.scenario_results
        )
        self.sensitivity_results = self._load_optional_csv(
            self.paths.sensitivity_results
        )
        self.scored_candidates_gdf = self._load_optional_geojson(
            self.paths.scored_candidates_geojson
        )
        self.selected_sites_gdf = self._load_optional_geojson(
            self.paths.selected_sites_geojson
        )

        self._validate_loaded_data()

        self._candidate_lookup = {
            _normalize_identifier(row["candidate_id"]): row
            for row in _records(self.candidates)
        }

    def _load_candidates(self) -> pd.DataFrame:
        path = self.paths.candidate_summary
        if not path.exists():
            return pd.DataFrame()

        with path.open("r", encoding="utf-8") as file:
            payload = json.load(file)

        if not isinstance(payload, list):
            raise TypeError(
                "agent_candidate_summary.json must contain a JSON list."
            )

        frame = pd.DataFrame(payload)

        if "candidate_id" in frame.columns:
            frame["candidate_id"] = (
                frame["candidate_id"].astype(str).str.strip()
            )

        return frame

    def _load_selected_sequence(self) -> pd.DataFrame:
        path = self.paths.selected_sequence
        if not path.exists():
            return pd.DataFrame()

        frame = pd.read_csv(path)

        if "candidate_id" in frame.columns:
            frame["candidate_id"] = (
                frame["candidate_id"].astype(str).str.strip()
            )

        if "selection_round" in frame.columns:
            frame["selection_round"] = pd.to_numeric(
                frame["selection_round"],
                errors="coerce",
            )
            frame = frame.sort_values(
                "selection_round",
                na_position="last",
            ).reset_index(drop=True)

        return frame

    def _load_configuration(self) -> dict[str, Any]:
        path = self.paths.configuration
        if not path.exists():
            return {}

        with path.open("r", encoding="utf-8") as file:
            payload = json.load(file)

        if not isinstance(payload, dict):
            raise TypeError(
                "planning_configuration.json must contain a JSON object."
            )

        return payload

    @staticmethod
    def _load_optional_csv(path: Path) -> pd.DataFrame | None:
        if not path.exists():
            return None

        frame = pd.read_csv(path)

        if "candidate_id" in frame.columns:
            frame["candidate_id"] = (
                frame["candidate_id"].astype(str).str.strip()
            )

        return frame

    @staticmethod
    def _load_optional_geojson(path: Path):
        if not path.exists() or gpd is None:
            return None

        data = gpd.read_file(path)

        if "candidate_id" in data.columns:
            data["candidate_id"] = (
                data["candidate_id"].astype(str).str.strip()
            )

        return data

    def _validate_loaded_data(self) -> None:
        if self.candidates.empty:
            if self.strict:
                raise ValueError(
                    "The candidate summary is empty."
                )
            return

        required_candidate_columns = {
            "candidate_id",
            "overall_score",
            "demand_score",
            "coverage_score",
            "accessibility_score",
            "feasibility_score",
            "equity_score",
        }
        missing_candidate_columns = (
            required_candidate_columns - set(self.candidates.columns)
        )

        if missing_candidate_columns:
            raise KeyError(
                "Candidate summary is missing required columns: "
                f"{sorted(missing_candidate_columns)}"
            )

        duplicate_ids = self.candidates["candidate_id"].duplicated()
        if duplicate_ids.any():
            duplicates = (
                self.candidates.loc[
                    duplicate_ids,
                    "candidate_id",
                ]
                .astype(str)
                .tolist()
            )
            raise ValueError(
                "Candidate IDs must be unique. Duplicates: "
                f"{duplicates[:20]}"
            )

        score_columns = [
            "overall_score",
            "demand_score",
            "coverage_score",
            "accessibility_score",
            "feasibility_score",
            "equity_score",
        ]

        for column in score_columns:
            numeric = pd.to_numeric(
                self.candidates[column],
                errors="coerce",
            )
            invalid = numeric.notna() & ~numeric.between(0, 1)
            if invalid.any():
                raise ValueError(
                    f"{column} contains values outside [0, 1]."
                )

        if not self.selected_sequence.empty:
            required_sequence_columns = {
                "candidate_id",
                "selection_round",
            }
            missing_sequence_columns = (
                required_sequence_columns
                - set(self.selected_sequence.columns)
            )
            if missing_sequence_columns:
                raise KeyError(
                    "Selected sequence is missing: "
                    f"{sorted(missing_sequence_columns)}"
                )

            if self.selected_sequence["candidate_id"].duplicated().any():
                raise ValueError(
                    "Selected sequence contains duplicate candidate IDs."
                )

            unknown = set(
                self.selected_sequence["candidate_id"]
            ) - set(self.candidates["candidate_id"])

            if unknown:
                raise ValueError(
                    "Selected sequence contains IDs absent from the "
                    f"candidate summary: {sorted(unknown)}"
                )

        weights = self.configuration.get("category_weights")
        if isinstance(weights, dict) and weights:
            weight_sum = sum(
                float(value)
                for value in weights.values()
            )
            if not math.isclose(
                weight_sum,
                1.0,
                rel_tol=1e-9,
                abs_tol=1e-9,
            ):
                raise ValueError(
                    "Configuration category weights do not sum to 1."
                )

    def file_status(self) -> dict[str, Any]:
        """Return required and optional evidence-file availability."""
        rows = []

        required_names = {
            "candidate_summary",
            "selected_sequence",
            "configuration",
        }

        for name, path in self.paths.__dict__.items():
            rows.append(
                {
                    "name": name,
                    "required": name in required_names,
                    "exists": path.exists(),
                    "size_bytes": (
                        path.stat().st_size
                        if path.exists()
                        else None
                    ),
                    "path": str(path),
                }
            )

        return {
            "project_root": str(self.project_root),
            "files": rows,
        }

    def get_planning_configuration(self) -> dict[str, Any]:
        """
        Return the deterministic planning configuration, including weights,
        service radius, exclusions, and requested recommendation count.
        """
        return {
            "status": "ok",
            "configuration": _json_safe(self.configuration),
        }

    def list_available_metrics(self) -> dict[str, Any]:
        """
        List candidate fields that can be used for deterministic ranking and
        comparison. Numeric metrics include their preferred interpretation
        direction when known.
        """
        numeric_metrics = []

        for column in self.candidates.columns:
            numeric = pd.to_numeric(
                self.candidates[column],
                errors="coerce",
            )
            if numeric.notna().any():
                numeric_metrics.append(
                    {
                        "metric": column,
                        "non_missing_count": int(
                            numeric.notna().sum()
                        ),
                        "preferred_direction": (
                            METRIC_DIRECTIONS.get(
                                column,
                                "not_defined",
                            )
                        ),
                    }
                )

        return {
            "status": "ok",
            "candidate_count": int(len(self.candidates)),
            "numeric_metrics": numeric_metrics,
            "all_fields": self.candidates.columns.tolist(),
        }

    def list_candidate_ids(
        self,
        limit: int = 50,
    ) -> dict[str, Any]:
        """
        Return valid candidate IDs and addresses. Use this before requesting
        evidence for an unfamiliar candidate ID.
        """
        limit = max(1, min(int(limit), 200))

        columns = [
            column
            for column in [
                "candidate_id",
                "address",
                "overall_score",
            ]
            if column in self.candidates.columns
        ]

        table = (
            self.candidates[columns]
            .sort_values(
                "overall_score",
                ascending=False,
                na_position="last",
            )
            .head(limit)
        )

        return {
            "status": "ok",
            "returned": int(len(table)),
            "total_candidates": int(len(self.candidates)),
            "candidates": _records(table),
        }

    def get_candidate(
        self,
        candidate_id: str,
    ) -> dict[str, Any]:
        """
        Return the complete compact evidence record for one candidate site.

        Args:
            candidate_id: Exact candidate ID, such as green_p_123.
        """
        normalized_id = _normalize_identifier(candidate_id)
        record = self._candidate_lookup.get(normalized_id)

        if record is None:
            return {
                "status": "error",
                "error": "unknown_candidate_id",
                "candidate_id": normalized_id,
                "suggestion": (
                    "Call list_candidate_ids to inspect valid IDs."
                ),
            }

        return {
            "status": "ok",
            "candidate": _json_safe(record),
        }

    def get_top_candidates(
        self,
        metric: str = "overall_score",
        n: int = 50,
        order: str = "desc",
    ) -> dict[str, Any]:
        """
        Return the top candidate sites for one existing numeric metric.

        Args:
            metric: Exact candidate-summary field used for sorting.
            n: Number of records to return, limited to 1 through 20.
            order: 'desc' for largest values or 'asc' for smallest values.
        """
        order = str(order).strip().lower()

        if order not in {"asc", "desc"}:
            return {
                "status": "error",
                "error": "invalid_order",
                "message": "order must be either 'asc' or 'desc'.",
            }

        if metric not in self.candidates.columns:
            return {
                "status": "error",
                "error": "unknown_metric",
                "metric": metric,
                "available_fields": self.candidates.columns.tolist(),
            }

        numeric = pd.to_numeric(
            self.candidates[metric],
            errors="coerce",
        )

        if numeric.notna().sum() == 0:
            return {
                "status": "error",
                "error": "metric_not_numeric",
                "metric": metric,
            }

        n = max(1, min(int(n), 20))

        table = self.candidates.copy()
        table["_sort_metric"] = numeric
        table = table[
            table["_sort_metric"].notna()
        ].sort_values(
            "_sort_metric",
            ascending=(order == "asc"),
        )

        preferred_fields = [
            "candidate_id",
            "address",
            metric,
            "overall_score",
            "demand_score",
            "coverage_score",
            "accessibility_score",
            "feasibility_score",
            "equity_score",
            "traffic_data_quality",
            "capacity_missing",
        ]

        columns = []
        for column in preferred_fields:
            if (
                column in table.columns
                and column not in columns
            ):
                columns.append(column)

        result = table[columns].head(n)

        return {
            "status": "ok",
            "metric": metric,
            "order": order,
            "preferred_direction": METRIC_DIRECTIONS.get(
                metric,
                "not_defined",
            ),
            "returned": int(len(result)),
            "candidates": _records(result),
        }

    def compare_candidates(
        self,
        candidate_ids: list[str],
        metrics: list[str] | None = None,
    ) -> dict[str, Any]:
        """
        Compare two to ten candidate sites using existing deterministic metrics.

        Args:
            candidate_ids: Exact candidate IDs to compare.
            metrics: Optional metric fields. When omitted, a standard evidence
                set is used.
        """
        normalized_ids = [
            _normalize_identifier(value)
            for value in candidate_ids
        ]

        if not 2 <= len(normalized_ids) <= 10:
            return {
                "status": "error",
                "error": "candidate_count_out_of_range",
                "message": (
                    "Provide between two and ten candidate IDs."
                ),
            }

        if len(set(normalized_ids)) != len(normalized_ids):
            return {
                "status": "error",
                "error": "duplicate_candidate_ids",
            }

        unknown = [
            candidate_id
            for candidate_id in normalized_ids
            if candidate_id not in self._candidate_lookup
        ]
        if unknown:
            return {
                "status": "error",
                "error": "unknown_candidate_ids",
                "candidate_ids": unknown,
            }

        metrics = metrics or DEFAULT_COMPARISON_METRICS
        missing_metrics = [
            metric
            for metric in metrics
            if metric not in self.candidates.columns
        ]

        if missing_metrics:
            return {
                "status": "error",
                "error": "unknown_metrics",
                "metrics": missing_metrics,
                "available_fields": self.candidates.columns.tolist(),
            }

        columns = [
            column
            for column in [
                "candidate_id",
                "address",
                *metrics,
                "traffic_data_quality",
                "capacity_missing",
            ]
            if column in self.candidates.columns
        ]

        comparison = (
            self.candidates
            .set_index("candidate_id")
            .loc[normalized_ids]
            .reset_index()[columns]
        )

        best_by_metric: dict[str, Any] = {}

        for metric in metrics:
            values = pd.to_numeric(
                comparison[metric],
                errors="coerce",
            )

            if values.notna().sum() == 0:
                best_by_metric[metric] = {
                    "status": "not_available",
                }
                continue

            direction = METRIC_DIRECTIONS.get(
                metric,
                "higher",
            )

            if direction == "lower":
                best_index = values.idxmin()
            else:
                best_index = values.idxmax()

            best_by_metric[metric] = {
                "candidate_id": comparison.loc[
                    best_index,
                    "candidate_id",
                ],
                "value": _json_safe(
                    comparison.loc[best_index, metric]
                ),
                "preferred_direction": direction,
            }

        baseline = comparison.iloc[0]
        differences_from_first: dict[str, Any] = {}

        for row_index in range(1, len(comparison)):
            row = comparison.iloc[row_index]
            candidate_differences: dict[str, Any] = {}

            for metric in metrics:
                first_value = pd.to_numeric(
                    pd.Series([baseline[metric]]),
                    errors="coerce",
                ).iloc[0]
                candidate_value = pd.to_numeric(
                    pd.Series([row[metric]]),
                    errors="coerce",
                ).iloc[0]

                if pd.isna(first_value) or pd.isna(candidate_value):
                    candidate_differences[metric] = None
                else:
                    candidate_differences[metric] = float(
                        candidate_value - first_value
                    )

            differences_from_first[
                str(row["candidate_id"])
            ] = candidate_differences

        return {
            "status": "ok",
            "candidate_ids": normalized_ids,
            "metrics": metrics,
            "records": _records(comparison),
            "best_by_metric": _json_safe(best_by_metric),
            "difference_reference_candidate": normalized_ids[0],
            "differences_from_first": _json_safe(
                differences_from_first
            ),
        }

    def get_selected_sequence(
        self,
        n: int = 50,
    ) -> dict[str, Any]:
        """
        Return the ordered deterministic recommendation sequence.

        Args:
            n: Maximum number of selected sites to return, limited to 1-20.
        """
        if self.selected_sequence.empty:
            return {
                "status": "unavailable",
                "reason": (
                    "selected_site_sequence.csv is missing or empty."
                ),
            }

        n = max(1, min(int(n), 20))
        table = self.selected_sequence.head(n)

        return {
            "status": "ok",
            "returned": int(len(table)),
            "available": int(len(self.selected_sequence)),
            "selection": _records(table),
        }

    def get_scenario_results(
        self,
        scenario_name: str | None = None,
        n: int = 50,
    ) -> dict[str, Any]:
        """
        Return exported planning-scenario selections.

        Args:
            scenario_name: Optional exact scenario name. Omit to list scenarios.
            n: Maximum records returned per request.
        """
        if (
            self.scenario_results is None
            or self.scenario_results.empty
        ):
            return {
                "status": "unavailable",
                "missing_file": str(
                    self.paths.scenario_results
                ),
                "required_export": (
                    "scenario_table.to_csv("
                    "OUTPUT_DIR / 'scenario_results.csv', "
                    "index=False)"
                ),
            }

        table = self.scenario_results.copy()
        scenarios = (
            sorted(
                table["scenario"]
                .dropna()
                .astype(str)
                .unique()
                .tolist()
            )
            if "scenario" in table.columns
            else []
        )

        if scenario_name is None:
            return {
                "status": "ok",
                "available_scenarios": scenarios,
                "row_count": int(len(table)),
            }

        if "scenario" not in table.columns:
            return {
                "status": "error",
                "error": "scenario_column_missing",
            }

        filtered = table[
            table["scenario"].astype(str)
            == str(scenario_name)
        ].copy()

        if filtered.empty:
            return {
                "status": "error",
                "error": "unknown_scenario",
                "scenario_name": scenario_name,
                "available_scenarios": scenarios,
            }

        if "selection_round" in filtered.columns:
            filtered = filtered.sort_values(
                "selection_round"
            )

        n = max(1, min(int(n), 20))

        return {
            "status": "ok",
            "scenario": scenario_name,
            "returned": int(min(n, len(filtered))),
            "selection": _records(filtered.head(n)),
        }

    def get_sensitivity_results(
        self,
        n: int = 20,
        minimum_frequency: float = 0.0,
    ) -> dict[str, Any]:
        """
        Return candidates most robust to changes in category weights.

        Args:
            n: Maximum number of candidates, limited to 1-20.
            minimum_frequency: Minimum selection frequency from 0 to 1.
        """
        if (
            self.sensitivity_results is None
            or self.sensitivity_results.empty
        ):
            return {
                "status": "unavailable",
                "missing_file": str(
                    self.paths.sensitivity_results
                ),
                "required_export": (
                    "sensitivity_table.to_csv("
                    "OUTPUT_DIR / 'sensitivity_results.csv', "
                    "index=False)"
                ),
            }

        if (
            "selection_frequency"
            not in self.sensitivity_results.columns
        ):
            return {
                "status": "error",
                "error": "selection_frequency_column_missing",
            }

        try:
            minimum_frequency = float(minimum_frequency)
        except (TypeError, ValueError):
            return {
                "status": "error",
                "error": "invalid_minimum_frequency",
            }

        if not 0 <= minimum_frequency <= 1:
            return {
                "status": "error",
                "error": "minimum_frequency_out_of_range",
            }

        n = max(1, min(int(n), 20))

        table = self.sensitivity_results.copy()
        table["selection_frequency"] = pd.to_numeric(
            table["selection_frequency"],
            errors="coerce",
        )

        table = (
            table[
                table["selection_frequency"]
                >= minimum_frequency
            ]
            .sort_values(
                "selection_frequency",
                ascending=False,
            )
            .head(n)
        )

        return {
            "status": "ok",
            "minimum_frequency": minimum_frequency,
            "returned": int(len(table)),
            "candidates": _records(table),
        }

    def audit_candidate(
        self,
        candidate_id: str,
    ) -> dict[str, Any]:
        """
        Audit one candidate for missing evidence, weak data quality, exclusion
        conflicts, and invalid score values.
        """
        result = self.get_candidate(candidate_id)

        if result["status"] != "ok":
            return result

        candidate = result["candidate"]
        warnings: list[str] = []
        critical_issues: list[str] = []

        if candidate.get("capacity_missing") is True:
            warnings.append(
                "Parking capacity was missing and was imputed."
            )

        traffic_quality = str(
            candidate.get("traffic_data_quality") or ""
        ).lower()

        if traffic_quality == "low":
            warnings.append(
                "Traffic evidence has low spatial-proximity quality."
            )
        elif not traffic_quality:
            warnings.append(
                "Traffic data-quality label is unavailable."
            )

        required_evidence = [
            "overall_score",
            "demand_score",
            "coverage_score",
            "accessibility_score",
            "feasibility_score",
            "equity_score",
            "population_1000m",
            "distance_to_nearest_charger_m",
        ]

        missing_evidence = [
            field
            for field in required_evidence
            if candidate.get(field) is None
        ]

        if missing_evidence:
            warnings.append(
                "Missing evidence fields: "
                + ", ".join(missing_evidence)
            )

        score_fields = [
            "overall_score",
            "demand_score",
            "coverage_score",
            "accessibility_score",
            "feasibility_score",
            "equity_score",
        ]

        for field in score_fields:
            value = candidate.get(field)
            if value is None:
                continue

            try:
                numeric_value = float(value)
            except (TypeError, ValueError):
                critical_issues.append(
                    f"{field} is not numeric."
                )
                continue

            if not 0 <= numeric_value <= 1:
                critical_issues.append(
                    f"{field} is outside [0, 1]."
                )

        capacity = candidate.get("capacity_filled")
        if capacity is not None:
            try:
                if float(capacity) < 10:
                    critical_issues.append(
                        "Parking capacity is below the prototype "
                        "eligibility threshold."
                    )
            except (TypeError, ValueError):
                critical_issues.append(
                    "Parking capacity is not numeric."
                )

        exclusion_distance = self.configuration.get(
            "existing_charger_exclusion_m"
        )
        charger_distance = candidate.get(
            "distance_to_nearest_charger_m"
        )

        if (
            exclusion_distance is not None
            and charger_distance is not None
        ):
            try:
                if float(charger_distance) <= float(
                    exclusion_distance
                ):
                    critical_issues.append(
                        "Candidate conflicts with the existing-charger "
                        "exclusion distance."
                    )
            except (TypeError, ValueError):
                warnings.append(
                    "Could not verify existing-charger exclusion."
                )

        risk_level = (
            "high"
            if critical_issues
            else "medium"
            if warnings
            else "low"
        )

        return {
            "status": "ok",
            "candidate_id": _normalize_identifier(
                candidate_id
            ),
            "risk_level": risk_level,
            "critical_issues": critical_issues,
            "warnings": warnings,
            "approved_for_planning_screening": (
                len(critical_issues) == 0
            ),
        }

    def audit_recommendation_set(
        self,
        candidate_ids: list[str] | None = None,
        minimum_separation_m: float | None = None,
    ) -> dict[str, Any]:
        """
        Audit a recommendation set for unknown IDs, duplicates, maximum count,
        candidate-level warnings, and pairwise spacing when geometry is present.

        Args:
            candidate_ids: Candidate IDs to audit. When omitted, the exported
                selected sequence is used.
            minimum_separation_m: Optional spacing threshold. When omitted, the
                planning configuration value is used.
        """
        if candidate_ids is None:
            if self.selected_sequence.empty:
                return {
                    "status": "unavailable",
                    "reason": (
                        "No IDs were provided and the selected sequence "
                        "is unavailable."
                    ),
                }
            candidate_ids = (
                self.selected_sequence["candidate_id"]
                .astype(str)
                .tolist()
            )

        normalized_ids = [
            _normalize_identifier(value)
            for value in candidate_ids
        ]

        critical_issues: list[str] = []
        warnings: list[str] = []

        duplicate_ids = sorted(
            {
                candidate_id
                for candidate_id in normalized_ids
                if normalized_ids.count(candidate_id) > 1
            }
        )

        if duplicate_ids:
            critical_issues.append(
                "Duplicate candidate IDs: "
                + ", ".join(duplicate_ids)
            )

        unknown_ids = sorted(
            set(normalized_ids)
            - set(self._candidate_lookup)
        )

        if unknown_ids:
            critical_issues.append(
                "Unknown candidate IDs: "
                + ", ".join(unknown_ids)
            )

        configured_max = self.configuration.get(
            "number_of_recommendations"
        )

        if configured_max is not None:
            try:
                if len(normalized_ids) > int(configured_max):
                    critical_issues.append(
                        "Recommendation count exceeds the configured "
                        f"maximum of {int(configured_max)}."
                    )
            except (TypeError, ValueError):
                warnings.append(
                    "Configured recommendation count is not numeric."
                )

        candidate_audits = []
        for candidate_id in normalized_ids:
            if candidate_id in self._candidate_lookup:
                candidate_audits.append(
                    self.audit_candidate(candidate_id)
                )

        candidate_warning_count = sum(
            bool(audit.get("warnings"))
            for audit in candidate_audits
        )
        candidate_critical_count = sum(
            bool(audit.get("critical_issues"))
            for audit in candidate_audits
        )

        if candidate_critical_count:
            critical_issues.append(
                f"{candidate_critical_count} candidate audit(s) "
                "contain critical issues."
            )

        if candidate_warning_count:
            warnings.append(
                f"{candidate_warning_count} candidate audit(s) "
                "contain data-quality warnings."
            )

        separation_threshold = minimum_separation_m
        if separation_threshold is None:
            separation_threshold = self.configuration.get(
                "minimum_selected_site_separation_m"
            )

        geometry_audit: dict[str, Any] = {
            "status": "unavailable",
            "reason": (
                "Scored-candidate GeoJSON or GeoPandas is unavailable."
            ),
        }

        if (
            gpd is not None
            and self.scored_candidates_gdf is not None
            and "candidate_id"
            in self.scored_candidates_gdf.columns
            and separation_threshold is not None
            and not unknown_ids
            and len(set(normalized_ids)) >= 2
        ):
            selected_geometry = (
                self.scored_candidates_gdf[
                    self.scored_candidates_gdf[
                        "candidate_id"
                    ].isin(normalized_ids)
                ]
                .drop_duplicates("candidate_id")
                .copy()
            )

            if len(selected_geometry) != len(
                set(normalized_ids)
            ):
                missing_geometry_ids = sorted(
                    set(normalized_ids)
                    - set(
                        selected_geometry["candidate_id"]
                        .astype(str)
                    )
                )
                geometry_audit = {
                    "status": "partial",
                    "missing_candidate_ids": (
                        missing_geometry_ids
                    ),
                }
                warnings.append(
                    "Geometry is missing for some recommended sites."
                )
            else:
                analysis_crs = self.configuration.get(
                    "analysis_crs",
                    "EPSG:26917",
                )
                projected = selected_geometry.to_crs(
                    analysis_crs
                ).set_index("candidate_id")

                violations = []
                pairwise_distances = []

                ids = list(dict.fromkeys(normalized_ids))

                for first_index in range(len(ids)):
                    for second_index in range(
                        first_index + 1,
                        len(ids),
                    ):
                        first_id = ids[first_index]
                        second_id = ids[second_index]

                        distance = float(
                            projected.loc[
                                first_id
                            ].geometry.distance(
                                projected.loc[
                                    second_id
                                ].geometry
                            )
                        )

                        pairwise_distances.append(distance)

                        if distance < float(
                            separation_threshold
                        ):
                            violations.append(
                                {
                                    "candidate_id_1": first_id,
                                    "candidate_id_2": second_id,
                                    "distance_m": distance,
                                }
                            )

                geometry_audit = {
                    "status": "ok",
                    "threshold_m": float(
                        separation_threshold
                    ),
                    "minimum_pairwise_distance_m": (
                        min(pairwise_distances)
                        if pairwise_distances
                        else None
                    ),
                    "violation_count": len(violations),
                    "violations": violations,
                }

                if violations:
                    critical_issues.append(
                        f"{len(violations)} pairwise spacing "
                        "violation(s) were found."
                    )

        approved = len(critical_issues) == 0

        return {
            "status": "ok",
            "candidate_count": len(normalized_ids),
            "candidate_ids": normalized_ids,
            "critical_issues": critical_issues,
            "warnings": warnings,
            "candidate_audits": candidate_audits,
            "geometry_audit": _json_safe(
                geometry_audit
            ),
            "reviewer_approved": approved,
        }

    def create_llamaindex_tools(self) -> dict[str, Any]:
        """
        Wrap deterministic methods as LlamaIndex FunctionTool objects.

        Returns:
            Dictionary keyed by tool name.
        """
        try:
            from llama_index.core.tools import FunctionTool
        except ImportError as error:
            raise ImportError(
                "Install llama-index-core before creating tools: "
                "pip install llama-index-core"
            ) from error

        functions = [
            self.get_planning_configuration,
            self.list_available_metrics,
            self.list_candidate_ids,
            self.get_candidate,
            self.get_top_candidates,
            self.compare_candidates,
            self.get_selected_sequence,
            self.get_scenario_results,
            self.get_sensitivity_results,
            self.audit_candidate,
            self.audit_recommendation_set,
        ]

        tools = {}

        for function in functions:
            tool = FunctionTool.from_defaults(
                fn=function
            )

            # Build the Pydantic argument schema immediately so unresolved
            # annotations fail here rather than during an agent run.
            tool.metadata.get_parameters_dict()

            tools[function.__name__] = tool

        return tools

    def role_tool_names(self) -> dict[str, list[str]]:
        """
        Return recommended tool assignments for specialist GeoPlan agents.
        """
        return {
            "PlanningCoordinator": [
                "get_planning_configuration",
                "list_candidate_ids",
                "get_selected_sequence",
                "audit_recommendation_set",
            ],
            "DemandCoverageAgent": [
                "get_candidate",
                "get_top_candidates",
                "compare_candidates",
                "get_selected_sequence",
            ],
            "AccessibilityFeasibilityAgent": [
                "get_candidate",
                "get_top_candidates",
                "compare_candidates",
                "audit_candidate",
            ],
            "EquityRiskAgent": [
                "get_candidate",
                "compare_candidates",
                "audit_candidate",
                "audit_recommendation_set",
            ],
            "ScenarioAnalysisAgent": [
                "get_scenario_results",
                "get_sensitivity_results",
                "compare_candidates",
            ],
            "FinalReviewerAgent": [
                "get_planning_configuration",
                "get_candidate",
                "get_selected_sequence",
                "audit_candidate",
                "audit_recommendation_set",
            ],
        }

    def create_role_tool_groups(
        self,
    ) -> dict[str, list[Any]]:
        """
        Return LlamaIndex FunctionTool lists grouped by specialist-agent role.
        """
        tools = self.create_llamaindex_tools()
        return {
            role: [
                tools[name]
                for name in names
            ]
            for role, names in self.role_tool_names().items()
        }

    def save_tool_manifest(
        self,
        path: str | Path | None = None,
    ) -> Path:
        """
        Save a JSON manifest describing tool names and recommended agent roles.
        """
        target = Path(
            path
            or (
                self.output_dir
                / "agent_tool_manifest.json"
            )
        )

        target.parent.mkdir(
            parents=True,
            exist_ok=True,
        )

        manifest = {
            "project_root": str(self.project_root),
            "tool_names": list(
                self.create_llamaindex_tools().keys()
            ),
            "role_tool_names": self.role_tool_names(),
            "file_status": self.file_status(),
        }

        with target.open(
            "w",
            encoding="utf-8",
        ) as file:
            json.dump(
                _json_safe(manifest),
                file,
                indent=2,
            )

        return target
